[project]
name = "hw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "notebook>=7.4.7",
    "pgvector>=0.4.1",
    "polars>=1.35.2",
    "psycopg>=3.2.12",
    "sentence-transformers>=5.1.2",
    "sqlalchemy>=2.0.44",
]
